jobs:
    shellcheck:
        steps:
          - run:
                command: |
                    ./test.sh
                    shellcheck install.sh test.sh promptless.sh -e SC2148

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master

