jobs:
    build:
        machine: true
        steps:
            - run:
                name: Running tests
                command: ./test.sh
            - run:
                name: Shellceck
                command: shellcheck install.sh test.sh promptless.sh -e SC2148
